name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.1, 8.2]
        laravel: [9.*, 10.*]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{matrix.php}}
          extensions: mbstring, pdo_mysql, pdo_pgsql, gd, zip
          coverage: none
          ini-values: memory_limit=-1

      - name: Install dependencies
        run: composer install --no-interaction

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.json') }}
      - name: List Files (Debugging)
        run: ls -la  # List files to check if artisan is present

      - name: Run Statistics Tests
        env:
          APP_ENV: wakeb\statistics
          CACHE_DRIVER: array
          SESSION_DRIVER: array
          QUEUE_CONNECTION: sync
          DB_CONNECTION: sqlite
          DB_DATABASE: ':memory:'
        run: php artisan test --coverage-text

      - name: Linting
        run: composer run-script lint
